/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Fieldset: typeof import('primevue/fieldset')['default']
    Ini: typeof import('./src/components/Ini.vue')['default']
    Json: typeof import('./src/components/Json.vue')['default']
    Json5: typeof import('./src/components/Json5.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toml: typeof import('./src/components/Toml.vue')['default']
    Yaml: typeof import('./src/components/Yaml.vue')['default']
  }
}
